### ISSUE TITLE
Revoke current key got 412 Precondition Failed response

### ISSUE THREAD

**Issue by doggy8088** [remy/jsonbin#16]
When I make a `DELETE /_/me/apikey` request with current key, the response is `412 Precondition Failed` is a bit strange.  It do revoked.  I think it should be `204 No Content` or `200 OK` response.

**Comment by remy** [comment]
Makes sense, I realise the [redirect](https://github.com/remy/jsonbin/blob/master/lib/routes/me.js#L18) is the cause. It should just send the value back (along with delete of the old) with `201` (I think).
