### ISSUE TITLE
Permission seems wrong

### ISSUE THREAD

**Issue by doggy8088** [remy/jsonbin#17]
When I make a request to `PUT https://jsonbin.org/username/test/_perms`, the `https://jsonbin.org/username/test` will become public.  After the `/username/test` become public, all the url that prefix `/username/test` will become public.  This seems a bit problem.  For example, the url `/username/test123` still become public which means this is probably wrong.

**Comment by remy** [comment]
I did spot that a little time ago but thought I'd squashed it.

Maybe a test that confirms this would be a good start (there's automated
tests in the test directory if you want to have a go at a PR).

**Comment by remy** [comment]
Yeah, here https://github.com/remy/jsonbin/blob/master/lib/routes/api.js#L50

**Comment by doggy8088** [comment]
@remy Is this OK? https://github.com/remy/jsonbin/pull/18/files

**Comment by remy** [comment]
I need to add tests for it when I have time. I've not read the code in
detail yet either.
