### ISSUE TITLE
When to enable CORS?

### ISSUE THREAD

**Issue by David-Tsui** [remy/jsonbin#19]
As above, it would be better if it could be used in browsers, thx.

**Comment by remy** [comment]
Hmm, CORS was supposed to be there from day 1, but [testing in jsbin](https://jsbin.com/sagavuc/edit?js,console) it's not loading. I'll investigate.

**Comment by remy** [comment]
Fixed - thanks!

I've also added support for a bearer token which you can control the expiry of, so it's safer to use in the client rather than dropping your private api key in the browser.
