### ISSUE TITLE
patch <property>:null doesn't remove a property itself

### ISSUE THREAD

**Issue by srgg6701** [remy/jsonbin#21]
I have such an object: 
```
"blog": {
    "name": "srgg",
    "last name": "who knows",
    "moniker": {
      "first one": "Pierrot"
    }
  }
```
The following query:
```
$.ajax({
	headers: {
		authorization : "token <token>"
	},
	method: "patch",
	url: "https://jsonbin.org/<user_name>/blog",
	data: {"name":null}
});
```
... doesn't remove the property, but changes its value to the empty string:
`"name": ""`

**Comment by remy** [comment]
Hmm. I just wrote an automation test (so it's easy to say "start with this, do this, expect this") and it's passing for your situation. I then tried again manually and it's passing.

Can you check your network requests to ensure that a) it's going up a `application/json` and b) the `null` prop isn't being stripped (though it shouldn't, AKAIK only `undefined` will be stripped).

See files called `21.*`: https://github.com/remy/jsonbin/tree/master/tests/operations

**Comment by remy** [comment]
Going to close this, I'm pretty sure it's all good - the upshot: tests have been easier to contribute 😄
