### ISSUE TITLE
Public paths become 404 when logged in

### ISSUE THREAD

**Issue by millette** [remy/jsonbin#3]
From a private browser window, I get the expected result from GET https://jsonbin.org/remy/blog
```
{
  "title": "remy's b:log",
  "url": "https://remysharp.com"
}
```

But if I'm logged in jsonbin.org (via github), then I get a 404 for the same request.

**Comment by t-boom** [comment]
Same here. I'm assuming when logged in it tries to resolve `/remy/blog` against your personal store, and that may be expected behavior, but that's just a guess.

**Comment by remy** [comment]
Sod you're exactly right. Now wondering what the right path is here, since
`remy` could be a valid local path in your store.

Open to suggestions here…

**Comment by remy** [comment]
I had one thought that a non-auth header request could see public urls (which in the code is simple enough), but my concern with that approach is that it's inconsistent with usage using the auth header.

Because of this, I think I need to make a breaking change to the url structure, but just inserting a prefix in the root of the URL, so instead of `POST`ing to https://jsonbin.org/blog/url, I'd have to post to _something_ like https://jsonbin.org/me/blog/url

I'm not totally bought on the `me` url prefix, it could be the owner's username, but I'm not that keen either, or it could be `api`…

Open to views on this, or if it's not completely clear, let me know and I'll write out the possible URLs.

**Comment by remy** [comment]
On the back of this problem, I also know from experience with jsbin that this URL scheme I've started can get hairy, because you have to reserve a bunch of root URLs (preventing users from having them, like "help"), but I do also know that this works for Twitter as they have a similar scheme…

**Comment by sallar** [comment]
The "standard" approach to this would be using `username` prefix for public and private stores. so anything I do would be `/sallar/something/blah` no matter it's public or private. This way the URLs wont conflict. And about the concern of reserved words, it's also a standard practice to maintain a blacklist of usernames. Such as: help, information, support, contact, about, etc. Which I'm pretty sure somebody has already put together.

**Comment by claudiopro** [comment]
@remy I think you ought to add a path component for the user's personal store, e.g.

`https://jsonbin.org/my/blog`

This way, the first path component would _always_ represent a user's store, or your own.
 
Having two URLs map to the same resource when authenticated or not creates more ambiguity than benefits of a shorter path when authenticated.

**Comment by remy** [comment]
So, initial concensus is to always prefix with username for data management?

**Comment by remy** [comment]
Just as a heads up, I'm going to go ahead with making the `:username` a required prefix on the API. I'm updating the API, tests (and writing them!) and docs.

**Comment by remy** [comment]
Fixed and live.

It does mean that requests to the root path now return the homepage/man instead of your JSON. Obviously update to match your username.

**Comment by t-boom** [comment]
@remy So URLs for API access and public access will be the same?

**Comment by t-boom** [comment]
Also, `https://jsonbin.org/_/login` no longer works, nor does `https://jsonbin.org/:username/_/login`.

**Comment by remy** [comment]
@t-boom that's right.

**Comment by remy** [comment]
…but you still need to _make_ them public first (via a `PUT`).

**Comment by t-boom** [comment]
Males sense. Thanks for the clarification.
