### ISSUE TITLE
Invalid auth token provided

### ISSUE THREAD

**Issue by simon2d** [remy/jsonbin#30]
Hi,
I have entered my token number in autoweb/jsonbin.org web service.
It says: ready to use in green.

when I'm trying write a cloud variable in tasker, I always get this error:
15.22.29/E Error: 1867121445
15.22.29/E {  "message": "Invalid auth token provided",  "status": 412}

**Comment by remy** [comment]
It means you're not providing a valid API token or bearer token.

**Comment by simon2d** [comment]
I'm not sure what I'm missing but here's what I've done:

-installed autoweb
In autoweb
    -clicked on "your Web services"
    -pressed the plus sign
    -selected import
    -imported Jsonbin.org
    -when asked for a token, I entered my api key provided when I subscribed here: https://jsonbin.org/
   -the Jsonbin.org says Ready to Use in green (I'm assuming the token is correct at this point)

Open tasker
    -created a new profile State/wifi connected SSID "added my ssid"
   -create a task
        -create Alert/flash/%DEVMOD
    -create another task
        -create/plugin/AutoWeb/Web service
        -selected Jsonbin.org in API
        -API Action: Set Data For Keys
        -Key: %DEVMOD
        -Value: Home
    -Accept the changes.
    -run the task
    getting the error message

Any idea what I'm missing or doing wrong?

**Comment by remy** [comment]
I don't know what autoweb is, but I'd suggest starting with their support. I'd guess you're not setting the http headers required.

**Comment by simon2d** [comment]
Ok Thanks, I'll check with them
