### ISSUE TITLE
Topology was destroyed

### ISSUE THREAD

**Issue by cmelone** [remy/jsonbin#32]
Im getting a 500 error when trying to access the site

**Comment by remy** [comment]
Fixed. Cheers for the heads up.

**Comment by Liorfru** [comment]
It's back!

**Comment by remy** [comment]
Always worth opening a new issue for this one - but acknowledging 👍 pushing a fix shortly (a redeploy and *hopefully* a change that should reconnect if this happens again)

**Comment by remy** [comment]
New version is live now - thanks for the heads up @Liorfru
