### ISSUE TITLE
JSON store too large prevents any further usage

### ISSUE THREAD

**Issue by bakapear** [remy/jsonbin#37]
```
{
"message": "The JSON store for \"bakapear\" is too large and can cause memory heap allocations failures. Please get in touch via the github issues to have your store manually reduced.",
"status": 500
}
```
I put a very large JSON object inside my store and would like it to get removed please. It's stored under /bakapear/tfvoices. I hope the other paths are still okay... :(

**Comment by remy** [comment]
sorry for dropping this - will close (given it's 1yr+ old) - ping a new issue if you're seeing new problems.

**Comment by bakapear** [comment]
It still gives me the message though :(

**Comment by remy** [comment]
@bakapear oh, it's because your store is too big and I can see from other issues that delete might be a problem… 

I'll check your record and see what's up.

**Comment by remy** [comment]
If curl/download your jsonbin.org/me url, do you get the full 1.19mb json?

**Comment by bakapear** [comment]
I cannot login to the site because of the error message and thus cannot retrieve my token to make the request.

**Comment by remy** [comment]
lol - of course, because it updates your last log in time, but then fails to write, and thus throws you out - okay, I need to fix that!

**Comment by remy** [comment]
Can you give that another try - I've made a small tweak to help you get back in.

**Comment by bakapear** [comment]
Thank you, everything works as intended now!
