### ISSUE TITLE
Topology was destroyed (500)

### ISSUE THREAD

**Issue by kkkrist** [remy/jsonbin#39]
I'm currently getting a 500 on all endpoints when I use this GitHub account (tried cookie and token auth). Could you please look into it? Thanks! 

```json
{
  "message": "Topology was destroyed",
  "status": 500
}
```

**Comment by remy** [comment]
Poop. Am on holiday and to kick this error requires a redeploy, which I
can't do (no access)

**Comment by kkkrist** [comment]
Enjoy your holiday! 🏝️
This can most certainly wait.

**Comment by shawntax** [comment]
Hiya @remy, I'm also getting the above `500`. This time when trying to login from the jsonbin homepage.

**Comment by remy** [comment]
Copying from email:

Hmm, looking into it now, it looks like some serious problem happened against the database. I'm investigating at the moment, but I'm a little worried that it was fatal…

**Comment by remy** [comment]
Okay, got a reply from mlab who host the database and the database was hosted on one of the permanently lost sandbox listed on their status page: https://status.mlab.com

The upside is that they've restored a system level backup - that from what I can tell  - is from last Friday (Aug-30) which is pretty good given the totality of the outage.

The site is back up and working.

Obviously this is one of the downsides of a completely free service - there's no guarantees. Which leads to the question of whether I ask for a small fee per year to cover backups and storage - or if we continue to manage our own backups (i.e. a cronjob on https://jsonbin.org/me would be a "personal" backup).

Doing rough back of the paper calcs, I reckon $15 per year would cover everything (backup runs, storage and payment handler fees - a price that I've factored myself paying as I use the service too).

Let me know what you all think.

**Comment by shawntax** [comment]
Thanks for looking into it--glad that things are back up and running!

I, personally, would be totally fine paying ~$15/year to help keep the lights on, and that extra reliability would encourage me to use `jsonbin` in more personal and even work-related projects. But I would expect that part of charging an annual fee would mean moving the service out of open beta, which would probably require more upkeep on your end. 

So the decision is really yours to make.

**Comment by kkkrist** [comment]
Frankly, I've grabbed the code and set up my own instance when jsonbin.org was down in early July. I'm maintaining a little server for some other Node.js/MongoDB-based projects anyway, so it wasn't a big deal. Dunno how you feel about this? I know it's MIT, but still.

~$15/year feels like a no-brainer though, even if it would be just to support the project.

**Comment by remy** [comment]
Indeed self hosting is a totally viable option. It might even make sense to
drop the dep on mongodb for sqlite - though depends entirely on how it's
hosted (ie. wouldn't suite a serverless setup - not that the codebase is
compatible with serverless anyway).
