### ISSUE TITLE
curl POST response not clear

### ISSUE THREAD

**Issue by senthilp** [remy/jsonbin#4]
Tried doing a curl POST 

`curl -H 'authorization: token <my-token>' -X POST https://jsonbin.org/senthilp/blog -d '{"url": "http://senthilp.com"}'`

and got a strange response
`{ "message": "The do`

When I later hit the URL [https://jsonbin.org/blog](https://jsonbin.org/blog) in a browser, I got the below response
```json
{
  "message": "Not Found"
}
``` 
Not sure if I am doing anything wrong here. I logged in to GitHub, obtained my apikey and it works for other endpoints like `curl -H 'authorization: token <my-token>' -X GET https://jsonbin.org/_/me`

**Comment by remy** [comment]
Can you try the post again? I've been tweaking the parser that reads the
body for different content types so you might have caught me in between a
duff release (I'm trying to capture all the request permutations in tests).

Your POST looks right to me otherwise.

**Comment by remy** [comment]
Also, I tweaked the API slightly (well, in a major way) so that when you
hit the browser URL, you'll need to include your username in the request
)if you're signed in via the browser, it should load as an auth'ed request.

**Comment by remy** [comment]
I was just able to test on my phone and I get 422. As a quick workaround I'm pretty sure if you add a json content type it'll work, and I'll get on fixing it.

**Comment by senthilp** [comment]
Tried again `curl -H 'authorization: token <my-token>' -X POST https://jsonbin.org/senthilp/blog1 -d '{"url": "http://senthilp.com"}'`, this time got the below message 
```json
{
  "message": "Unprocessable Entity"
}
```

**Comment by remy** [comment]
That's fixed and live. Thanks for filing the issue.

**Comment by senthilp** [comment]
Works perfectly. Thanks.
