### ISSUE TITLE
500 when updating one of my bins

### ISSUE THREAD

**Issue by NeuroAssassin** [remy/jsonbin#40]
I'm getting a 500 error when updating one of my bins.  Was working perfectly fine before I added an extra key/value pair to the main dictionary (or object, if you prefer).  After that, just responds with 500 + "Something went wrong" in the JSON.  I can still get the json however, I just can't update the data in it.  I'm willing to submit more info if needed.

**Comment by alecuba16** [comment]
I'm also getting 502 with DELETE of any bin, which is a random error. It is generated sometimes.

**Comment by remy** [comment]
I'm going to close this as it took me 4 years to reply 😬  - but if it's still a problem, please ping me and I'll reopen and fix (much faster than 4 years!)
