### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by ekkis** [remy/jsonbin#43]
I logged into the jsonbin.org site and it provided me with an api key, as well as a curl statement I can run:
```
curl -X POST https://jsonbin.org/ekkis/blog \
      -H 'authorization: token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' \
      -d '{ url: "https://remysharp.com" }'
```
but that doesn't work:

> {
>   "message": "Unprocessable Entity",
>   "status": 422
> }

help?

I'm running this on OSX 10.14.6 and:
```
 $ curl --version
```

> curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
> Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

**Comment by remy** [comment]
This should be fixed - please give it a try and let me know.

**Comment by ekkis** [comment]
yes, now I get back the object I sent, which I gather is confirmation it was written to the store.  thanks for fixing this and sorry I couldn't be more help in identifying the problem.  I did spend some time with the code but it wasn't immediately obvious

also, thank you for writing this and maintaining it.  it is REALLY useful
