### ISSUE TITLE
HTTP 500: Topology destroyed

### ISSUE THREAD

**Issue by richterm** [remy/jsonbin#45]
Hi,

I just encountered the 500 error with the response

`{
  "message": "Topology was destroyed",
  "status": 500
}`

again. It was reported in September 2019 but could be fixed back then (see https://github.com/remy/jsonbin/issues/39).

Any luck now..?

Thanks in advance and for the great work with this project!

Max

**Comment by remy** [comment]
Closing - fixed. I keep trying to get the code right to recover from these disconnects, hopefully the code upgrade did the trick
