### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by umaar** [remy/jsonbin#48]
Hey! This is a really cool service for the community thank you 👍🏼️

Any quotas/limits we should be aware of? For example would storing a small JSON payload every few minutes be an acceptable use of your service?

Just wanted to check I'm using this reasonably!

**Comment by remy** [comment]
Hey @umaar - so there's no limits on sending, but a limit of 1000000 bytes (yeah, sorry, daft number) is imposed on the *entire* json store (not the individual payloads). 

It's currently running on a boosted glitch instance (which…I'm not so sure about).

The database is in a free tier mongodb and I've had an offline change that asks for a yearly subscription to help support the costs of database backups (i.e. free hosting is fine, but I want to be able to rely on the data) - perhaps I should put it up and make it voluntary (though that rarely pans out).

But be sensible with the service is all I ask. So maybe don't set a cronjob to run every 1 minute against the service :)

**Comment by umaar** [comment]
Got it! Thanks for explaining 👍️
