### ISSUE TITLE
Help clearing my store

### ISSUE THREAD

**Issue by fhur** [remy/jsonbin#49]
Hey there! I accidentally uploaded a few files that were to big. Would you please help me by clearing my store:

Please clear everything on `https://jsonbin.org/fhur/`

```
{
  "message": "The JSON store for \"fhur\" is too large and can cause memory heap allocations failures. Please get in touch via the github issues to have your store manually reduced.",
  "status": 500
}
```

**Comment by remy** [comment]
Darnit - I need to solve how to flag this _before_ the data is saved.

Do you want the entire thing cleared or a specific key?

**Comment by fhur** [comment]
Yeah, the whole thing would be great.

I tried deleting it myself (with the DELETE method), but I got the same error.

Awesome API, btw! Its been a huge time-saver.

**Comment by remy** [comment]
Instant service at 3 years and several months! I've (finally) cleared your storage.
