### ISSUE TITLE
Patch but not post on root

### ISSUE THREAD

**Issue by t-boom** [remy/jsonbin#5]
Sending a patch to your root works:

```bash
curl -H "Authorization: token <token>" \
    -H "Content-Type: application/json" \
    -X PATCH https://jsonbin.org/:user \  # PATCHing to the user root works
    -d "{ <json-data> }"
```

but posting to your root does not work:

```bash
curl -H "Authorization: token <token>" \
    -H "Content-Type: application/json" \
    -X POST https://jsonbin.org/:user \  # POSTing to the user root fails
    -d "{ <json-data> }"
```

Is this by design?

**Comment by t-boom** [comment]
If it is, it would be nice to see this mentioned in the help. It took me a while to figure out why my script wasn't working.

**Comment by remy** [comment]
Hmm, no, `POST` should definitely work. It acts as an overwrite. I'll take
a look (and I should be able to over it with a test too).

**Comment by remy** [comment]
Fix is now live (and also includes test coverage) and added support for "JSON merge patch (RFC 7396) ", examples [here](https://jsonbin.org/#notes-on-patch). Thanks for filing.

**Comment by t-boom** [comment]
Sweet, thanks
