### ISSUE TITLE
Glitch waking up page

### ISSUE THREAD

**Issue by sandysandy** [remy/jsonbin#50]
API requests are timing out for me and http://jsonbin.org/ Seems to bin stuck on the Glitch waking up screen. Is this an issue for anyone else? Raised here but seems like it might be a Glitch problem.

![5B5493BE-AA21-4C98-81E9-E152649ADFEC](https://user-images.githubusercontent.com/2616002/88818712-ea194880-d1b6-11ea-8f08-16f741a25eeb.png)

**Comment by remy** [comment]
I've contacted glitch support - no idea what's going on here (it's a boosted app and shouldn't be doing this).

**Comment by sandysandy** [comment]
Seems to be restored now. Thanks for the quick response.
