### ISSUE TITLE
jsonbin.org down AGAIN

### ISSUE THREAD

**Issue by Prabesh01** [remy/jsonbin#54]
its down. home page is blank. cant access data through endpoints

**Comment by remy** [comment]
Do you care to explain the caplocks, because it's coming across rather entitled...

Happy to take a look right after I get a reply.

**Comment by Prabesh01** [comment]
well i saw few past issues that were about jsonbin.org being down. 
So, wrote "AGAIN" 

hehe

**Comment by remy** [comment]
This is glitch and it's back.
