### ISSUE TITLE
https seems to be down.

### ISSUE THREAD

**Issue by romaia** [remy/jsonbin#58]
First of all, thanks for the great service provided.

Since 28/03, https is not working, but I do manage to access the data using http.

**Comment by epassaro** [comment]
Yep, the site is down :(

**Comment by remy** [comment]
Yeah, i know, been trying to bring it back. I'm actively working on it.

**Comment by romaia** [comment]
Everything seems to be back up again. Thanks @remy.

I'll leave the issue open if you want to follow up something...
