### ISSUE TITLE
The system seems to be unstable.

### ISSUE THREAD

**Issue by ythmobile** [remy/jsonbin#62]
The system seems to be unstable these past few days. I have opened the homepage(https://jsonbin.org/) several times then it appears (now it is):
>We're sorry, but something wet wrong
>If you are the application owner checking the logs for more information

Then, sometimes the homepage can be accessed normally, and during POST, an error of "422 Unprocessable Entity" appears again.
I hope @remy can fix it quickly. Thank you for your hard work.

**Comment by remy** [comment]
I'll get on it today. It's weird because it's been stable for years and this week I started looking at issues and now (of course) it's playing up!

My guess is something is causing it to explode - but I'll find out properly once I pop the hood on the machine.

**Comment by remy** [comment]
![SCR-20231026-kbdm-min](https://github.com/remy/jsonbin/assets/13700/8fee8331-25cb-41a1-a3b3-7a31613e300f)

What happened was the db size tipped over the limit and prevented the app from running/crashed. For some reason the sessions are growing and not cleaning up, so I had something like 400mb of session keys in there. I've nuked the table for now (and it automatically gets recreated) so it's back down, but I'm going to move the database inhouse to prevent the limit.
