### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by rlaurente** [remy/jsonbin#66]
Hi there

I'm not sure if it's only me but it seems the service is down. 

Thanks

**Comment by remy** [comment]
Definitely down. Though it's actually the DNS routing, the backend of the service is fine (and more importantly, so is the data).

I'm working on fixing it, but got personal stuff that's taking priority at the moment, so it's going to likely be a few days. Sorry.

I'll use this issue to keep ppl posted.

**Comment by rlaurente** [comment]
no worries, this service is amazing though! 
Thanks for providing this service

**Comment by remy** [comment]
starting to come back now - I've been able to sign in and it's working, but dns will need to propagate.

**Comment by gerkim62** [comment]
I don't know if it is only me, but my code for sending some object to an array hosted at jsonbin was working well previously but since  the recent incident, it is returning 

{
  "message": "Invalid JSON structure",
  "status": 422
}
422
Unprocessable Entity
. i havent touched the code

**Comment by remy** [comment]
@gerkim62 I'll need a sample of repeatable code.
