### ISSUE TITLE
Configurable endpoints and branding

### ISSUE THREAD

**Issue by theluk** [remy/jsonbin#7]
great idea and work! 

As it is MIT and here on github in its full beauty, it would make sense to make it easy after a fork to change the http endpoint etc. also a custom server installation readme would be nice.

**Comment by theluk** [comment]
... or do you plan to make it open just during beta?

**Comment by remy** [comment]
I can add an example `.env` file which shows what's required to deploy on a custom/alternative domain.

Re: open during beta - I _think_ my plan is to keep it as open source, and that I'll possibly add some added value layer on top of the current offering (like webhooks on data change, user backups, alternative stores…). 

My plan was to support 3 tiers of users: free (possibly limit the amount of requests or data…unsure exactly right now), supporter (unlimited data, but no additional features) and pro (i.e. all added features).

But it all really comes down to demand!

**Comment by remy** [comment]
I've included a sample `.env` file for running your own version: https://github.com/remy/jsonbin/blob/master/example.env

I'm going to close for now if that's cool?
