### ISSUE TITLE
Add CORS origins configs to all urls

### ISSUE THREAD

**Issue by doggy8088** [remy/jsonbin#8]
For request methods other than GET should have it's own CORS origins setup in order to send RESTful request from specific domain.

**Comment by remy** [comment]
Currently there's CORS in effect on [all GET requests](https://github.com/remy/jsonbin/blob/master/lib/routes/utils.js#L9-L14) - is this what you meant, or do you mean that you'd want to control exactly *which* origins could request?

**Comment by doggy8088** [comment]
I mean I need CORS support for `POST`/`DELETE`/`PUT`/`PATCH` verb for private bins with `apikey` provided.

**Comment by remy** [comment]
Sure, I'm happy to take a PR that adds CORS for the verbs if a valid API key is provided (it should correctly error if the API key doesn't have access to write to the endpoint so the test can be fairly minimal).
